gpio.mode(4,gpio.INPUT,gpio.PULLUP)
srv = net.createServer(net.TCP)
srv:listen(80, function(conn)
    conn:on("receive", function(sck, payload)
        print(payload)
        sck:send(string.format("<!doctype html><html><head><meta http-equiv=\"refresh\" content=\"2\"></head><body style=\"background:red;\"><h1 style=\"border-style:solid;border-color:white;border-width:10px;color:white;text-align:center;font-size:72px;background:black;\">%s</h1></body></html>",gpio.read(4)))
    end)
    conn:on("sent", function(sck) sck:close() end)
end)
