gpio.mode(4,gpio.INPUT,gpio.PULLUP)
srv = net.createServer(net.TCP)
srv:listen(80, function(conn)
    conn:on("receive", function(sck, payload)
        print(payload)
        sck:send(string.format("%s",gpio.read(4)))
    end)
    conn:on("sent", function(sck) sck:close() end)
end)